config/routes.rb
BikeHp::Application.routes.draw do
  root to: "top#index"

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :logout

  resources  :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :released_at, :expired_at, :member_only, :no_expiration
  attr_accessor :no_expiration
  before_validation :clear_expired_at
  validates :title, :body, :released_at, presence: true
  validates :title, length: {maximum: 200}


  class << self 
  def sidebar_article(num=5, current_user)
    if current_user
      rel = Article.order("released_at DESC").limit(num)
    else
      rel = Article.where(member_only: false).order("released_at DESC").limit(num)
    end 
  end 
  end 

  def no_expiration=(val)
    @no_expiration = val.in?([true, 1, "1"])
  end 


  private
  def clear_expired_at
  	self.expired_at = nil if @no_expiration
  end 


  def check_expired_at
  	if expired_at && expired_at < releasde_at
  		errors.add(:expired_at, :expired_at_too_old)
  	end 
  end 




end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  
  def self.create_with_omniauth(auth)
  	create! do |user|
  		user.provider = auth["provider"]
  		user.uid = auth["uid"]
  		user.name = auth["info"]["name"]
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :current_user

private
def current_user
	if session[:user_id]
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
		return @current_user
	end 
	return @current_user
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.order("released_at DESC")		
	end 

	def new
		@article = Article.new
	end

	def show
		@article = Article.find(params[:id])
	end 

	def create
		@article = Article.new(params[:article])
		if @article.save
			redirect_to articles_path, notice: "saved"
		else
			render "new"
		end 
	end 


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		auth = request.env["omniauth.auth"]
		user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
		session[:user_id] = user.id
		redirect_to root_path, :notice => "Signed in!"
	end
	
	def destroy
		session[:user_id] = nil
		redirect_to root_url  :notice => "Signed out!"
	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	before_filter :current_user
	def index 
		@message = "Hello World"
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/articles/index.html.erb
<div id="main">
<% @page_title = "記事一覧" %>
<h2><%= @page_title %></h2>
<h3><%= link_to "新規作成", new_article_path %></h3>
<% if @current_user %>
	<% if @articles.present? %>
	<% @articles.each do |article| %>
	<h2><%= article.title %></h2>
	<p><%= truncate(article.body, length: 80) %>
	<%= link_to "Read More", article_path(article) %></p>
	<% end %>
	<% else %>
	<p>No Article</p>
	<% end %>
<% end %>
</div>

app/views/articles/new.html.erb
<% @page_title = "記事の新規登録" %>
<h2><%= @page_title %></h2>

<%= form_for @article do |f| %>
	<%= render "./shared/form", form: f %>
	<p><%= f.submit %></p>
<% end %>

app/views/articles/show.html.erb
<table class="article_table">
	<tr>
		<th>タイトル</th>
		<th>掲載開始日</th>
		<th>掲載終了日</th>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>BikeHp</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "normailze", :media => "all" %>
  <%= stylesheet_link_tag    "base", :media => "all" %>
  <%= stylesheet_link_tag     "table", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "main" %>

  <%= csrf_meta_tags %>
  </head>
  <body>
  <div id="container">
    <%= render "shared/header" %>    
    <div id="wrapper">
      <%= render "shared/sidebar" %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shared/_form.html.erb
<table class="attr">
	<tr>
		<th><%= form.label :title %></th>
		<td><%= form.text_field :title, size: 20 %></td>
	</tr>
	<tr>
		<th><%= form.label :body %></th>
		<td><%= form.text_area :body, size: 20 %></td>
	</tr>
	<tr>
		<th><%= form.label :released_at, for: "article_released_at_1i" %></th>		
		<td><%= form.datetime_select :released_at, atrt_year: 2000, end_year: Time.now.year+1, use_month_numbers: true %></td>
	</tr>
	<tr>
		<th><%= form.label :expired_at, for: "article_expired_at_1i" %></th>
		<td>
			<%= form.check_box :no_expiration %>
			<%= form.label :no_expiration %><br />
			<%= form.datetime_select :expired_at, start_year: 2000, end_year: Time.now.year+1, use_month_numbers: true %>
		</td>
	</tr>
	<tr>
		<th><%= Article.human_attribute_name(:member_only) %></th>
		<td>
			<%= form.check_box :member_only %>
			<%= form.label :member_only %>
		</td>
	</tr>


</table>

app/views/shared/_header.html.erb
<div id="header">
	<% if @current_user %> 
	<p>ようこそ<%= @current_user.name %>さん |<%= link_to "記事一覧", articles_path%>  |   <%= link_to "Home", root_path%>  |  <%= link_to "Sign Out", logout_path %></p> 
	<% else %>
	<p>  <%= link_to "Sign in with Twitter", "/auth/facebook" %> </p>
	<% end %>
</div>

app/views/shared/_sidebar.html.erb
<div id = "submenu">
	<h1>
		<a href="#">
			<%= image_tag("logo.gif") %>
		</a>
	</h1>
	<% if Article.sidebar_article(5, @current_user) %>
	<% Article.sidebar_article(5, @current_user).each do |article| %>
	<p><%= link_to article.title, article_path(article) %></p>
	<% end %>
	<% else %>
	<p>記事がありません</p>
	<% end %> 
</div>

app/views/top/index.html.erb
		<div id="main">
			<div class="slideshow">
				<%= link_to image_tag("01.jpg"), "#" , class: "slide"%>
				<%= link_to image_tag("02.jpg"), "#" , class: "slide"%>
				<%= link_to image_tag("03.jpg"), "#" , class: "slide"%>
				<%= link_to image_tag("04.jpg"), "#" , class: "slide"%>
				<%= link_to image_tag("05.jpg"), "#" , class: "slide"%>
				<%= link_to image_tag("06.jpg"), "#" , class: "slide"%>
			</div>

			<ul class="info">	
 				<li><%= link_to "#" do %>
				<%= image_tag("info01.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info02.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info03.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info04.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info05.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info06.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info07.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info08.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

 				<li><%= link_to "#" do %>
				<%= image_tag("info09.png", {class: "info_img"})%><span></span>
				<% end %>	</li>

			</ul>
</div> 	